
CREATE SEQUENCE public."soil_things_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;


CREATE TABLE public."SOIL_SITE" (
	"ID" int8 DEFAULT nextval('soil_things_id_seq') NOT NULL,
	"DESCRIPTION" text NULL,
	"PROPERTIES" text NULL,
	"NAME" text NULL DEFAULT 'no name'::text,
	CONSTRAINT "SOIL_SITE_THINGS_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE public."SOIL_PLOT" (
	"ID" int8 DEFAULT nextval('soil_things_id_seq') NOT NULL,
	"DESCRIPTION" text NULL,
	"PROPERTIES" text NULL,
	"NAME" text NULL DEFAULT 'no name'::text,
	"LOCATED_ON" int8,
	-- Inverse association role "IS_OBSERVED_ON_LOCATION"
	CONSTRAINT "SOIL_PLOT_THINGS_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "SOIL_PLOT_SITE_FKEY" FOREIGN KEY ("LOCATED_ON") REFERENCES "SOIL_SITE"("ID") ON UPDATE CASCADE
);

CREATE TABLE public."SOIL_PROFILE" (
	"ID" int8 DEFAULT nextval('soil_things_id_seq') NOT NULL,
	"DESCRIPTION" text NULL,
	"PROPERTIES" text NULL,
	"NAME" text NULL DEFAULT 'no name'::text,
	"PLOT_LOCATION" int8,
	-- Inverse association role "OBSERVED_PROFILE"
	CONSTRAINT "SOIL_PROFILE_THINGS_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "SOIL_PROFILE_PLOT_FKEY" FOREIGN KEY ("PLOT_LOCATION") REFERENCES "SOIL_PLOT"("ID") ON UPDATE CASCADE
);

CREATE TABLE public."SOIL_HORIZON" (
	"ID" int8 DEFAULT nextval('soil_things_id_seq') NOT NULL,
	"DESCRIPTION" text NULL,
	"PROPERTIES" text NULL,
	"NAME" text NULL DEFAULT 'no name'::text,
	"IS_PART_OF" int8,
	-- Inverse association role "IS_DESCRIBED_BY"
	CONSTRAINT "SOIL_HORIZON_THINGS_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "SOIL_HORIZON_PROFILE_FKEY" FOREIGN KEY ("IS_PART_OF") REFERENCES "SOIL_PROFILE"("ID") ON UPDATE CASCADE
);


CREATE TABLE public."SOIL_LAYER" (
	"ID" int8 DEFAULT nextval('soil_things_id_seq') NOT NULL,
	"DESCRIPTION" text NULL,
	"PROPERTIES" text NULL,
	"NAME" text NULL DEFAULT 'no name'::text,
	"IS_PART_OF" int8,
	-- Inverse association role "IS_DESCRIBED_BY"
	CONSTRAINT "SOIL_LAYER_THINGS_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "SOIL_LAYER_PROFILE_FKEY" FOREIGN KEY ("IS_PART_OF") REFERENCES "SOIL_PROFILE"("ID") ON UPDATE CASCADE
);

CREATE TABLE public."SOIL_BODY" (
	"ID" int8 DEFAULT nextval('soil_things_id_seq') NOT NULL,
	"DESCRIPTION" text NULL,
	"PROPERTIES" text NULL,
	"NAME" text NULL DEFAULT 'no name'::text,
	"IS_DESCRIBED_BY" int8,
	-- Inverse association role not defined, I'd call it "HAS_BODY"
	CONSTRAINT "SOIL_BODY_THINGS_PKEY" PRIMARY KEY ("ID"),
	CONSTRAINT "SOIL_BODY_PROFILE_FKEY" FOREIGN KEY ("IS_DESCRIBED_BY") REFERENCES "SOIL_PROFILE"("ID") ON UPDATE CASCADE
);


CREATE OR REPLACE VIEW "THINGS" AS
SELECT "ID", "DESCRIPTION", "PROPERTIES", "NAME" FROM "SOIL_SITE"
UNION
SELECT "ID", "DESCRIPTION", "PROPERTIES", "NAME" FROM "SOIL_PLOT"
UNION
SELECT "ID", "DESCRIPTION", "PROPERTIES", "NAME" FROM "SOIL_PROFILE"
UNION
SELECT "ID", "DESCRIPTION", "PROPERTIES", "NAME" FROM "SOIL_HORIZON"
UNION
SELECT "ID", "DESCRIPTION", "PROPERTIES", "NAME" FROM "SOIL_LAYER"
UNION
SELECT "ID", "DESCRIPTION", "PROPERTIES", "NAME" FROM "SOIL_BODY"
;


